
DEFAULT_STARTER_STAMINA_MIN = 40
DEFAULT_STARTER_STAMINA_MAX = 80
DEFAULT_STARTER_CONTROL_MIN = 20
DEFAULT_STARTER_CONTROL_MAX = 80
DEFAULT_STARTER_VELO_MIN = 20
DEFAULT_STARTER_VELO_MAX = 80
DEFAULT_STARTER_MOVEMENT_MIN = 20
DEFAULT_STARTER_MOVEMENT_MAX = 80

DEFAULT_RELIEVER_STAMINA_MIN = 20
DEFAULT_RELIEVER_STAMINA_MAX = 40
DEFAULT_RELIEVER_CONTROL_MIN = 20
DEFAULT_RELIEVER_CONTROL_MAX = 80
DEFAULT_RELIEVER_VELO_MIN = 20
DEFAULT_RELIEVER_VELO_MAX = 80
DEFAULT_RELIEVER_MOVEMENT_MIN = 20
DEFAULT_RELIEVER_MOVEMENT_MAX = 80

DEFAULT_CLOSER_STAMINA_MIN = 20
DEFAULT_CLOSER_STAMINA_MAX = 40
DEFAULT_CLOSER_CONTROL_MIN = 20
DEFAULT_CLOSER_CONTROL_MAX = 80
DEFAULT_CLOSER_VELO_MIN = 20
DEFAULT_CLOSER_VELO_MAX = 80
DEFAULT_CLOSER_MOVEMENT_MIN = 20
DEFAULT_CLOSER_MOVEMENT_MAX = 80

